README.md
The README currently states that the default value for `PGBOUNCER_LOG_CONNECTIONS`, `PGBOUNCER_LOG_DISCONNECTIONS`, and `PGBOUNCER_LOG_POOLER_ERRORS ` is `yes`.  However, the actual value used is `1`, and using `yes` or `no` instead of `1` or `0` causes pgbouncer to crash with the not-so-descriptive error message of `Cannot load config file`.  This PR corrects the README to state that the default value is `1`.
Note that this is especially confusing because the setting described just prior to these three is `PGBOUNCER_CONNECTION_RETRY`, which is actually an stunnel setting and does use `yes`/`no` values.
=> corrected default values for logging settings

README.md, bin/gen-pgbouncer-conf.sh
The default stunnel loglevel is "notice", which is a bit too verbose for my taste (it logs messages every time a connection is created or disconnected).  
This PR adds another config environment variable (`PGBOUNCER_STUNNEL_LOGLEVEL`) which can be set in order to pass a non-default value to the stunnel config.
The default remains "notice", so unless this environment variable is set, this PR does not change the buildpack's behavior at all.
=> config option for stunnel logging level

bin/gen-pgbouncer-conf.sh
This allows the buildpack to function properly in Private Spaces.
=> Force using ipv4 locally

README.md
With `buildpacks:add` they don't need to specify a git url. THey can use `heroku/ruby` to get the deployed version.
=> Don't recommend master branch of Ruby buildpack

bin/gen-pgbouncer-conf.sh
Fixed the issue where the stunnel-pgbouncer.conf, user.txt and pgbouncer.ini files are being repeatedly appended on server restarts, instead of erasing and restarting.
Also fixed the DATABASE_URL parse to not fail on missing passwords.
=> Fixed continuous config appending

bin/gen-pgbouncer-conf.sh
The users.txt file must be appended to as multiple postgres dbs in
POSTGRES_URLS, we need to add all the creds to the users.txt file, not
reset it for every entry in POSTGRES_URLS.
=> Fix appending users.txt which broke in #83

README.md, bin/gen-pgbouncer-conf.sh
This should help to fix issues with go's pq driver. I'm using it on an example app right now and everything is working fine. Multiple parameters can be specified with commas.
=> Adding "ignore_startup_params" environment variable

README.md
This commit adds a note to the README about the expected format for
connection strings being passed as `PGBOUNCER_URLS`. Without this
format being respected, the connection string will be unable to be
parsed and unexpected errors may occur on connecting.
* Add note to README about expected connection string format
=> Add note about connection string format

bin/start-pgbouncer-stunnel
The wrapper script was previously creating a child process which messed up our signal trapping. Running `exec` should replace the current process with `bin/start-pgbouncer` which will trap kill signals and not exit until all of the child processes have exited.
The issue was that the wrapper script was creating `bin/start-pgbouncer` as a child process and not trapping any signals. Without the wrapper script `bin/start-pgbouncer` will trap signals, forward them to children, and wait until they have all exited cleanly before dying.
Should address https://github.com/heroku/heroku-buildpack-pgbouncer/issues/109.
=> Using exec in stunnel wrapper script

README.md
There are a double 'and' on the FAQ section
> ... connections and and ...
This pr fix it.
=> Removes double 'and' on the FAQ section

README.md, bin/gen-pgbouncer-conf.sh
This commit adds the `query_wait_timeout` configuration option
and associated `PGBOUNCER_QUERY_WAIT_TIMEOUT` env var for
configuration, in order to allow customisation of this option.
Default is set to 120 seconds, as per PgBouncer default.
=> Add query_wait_timeout configuration option

CONTRIBUTING.md, Changelog.md, Makefile, support/Dockerfile, support/docker-compose.yml, support/pgbouncer-build
hey everybody,
this PR provides some streamlining for the development and building process. it cuts down depdencies for development to just docker (without docker-compose) and running one command gives you the complete archive in the correct folder. this also makes it easier to add new stacks and change versions for certain stacks.
additionally i like to mirror the tooling across our buildpacks. this approachs mirrors how we build nginx https://www.github.com/heroku/heroku-buildpack-nginx
i rebuilt pgbouncer 1.7.2 and verified the new tooling on a personal test app.
let me know what you think.
cheers
ben
=> Overhaul development tooling

README.md
This ENV var was removed by https://github.com/heroku/heroku-buildpack-pgbouncer/commit/75d70dd7daf3777849a711b520b57d00ea85c647, but is still present in README
=> Remove PGBOUNCER_CONNECTION_RETRY from README.md

README.md
The old link to the feature matrix didn't work anymore.
This links to the correct page. 
It took me a while to find it, so I think it would be good to have the correct link here.
=> [Docs] Correct link to feature matrix

Changelog.md, README.md, bin/gen-pgbouncer-conf.sh, test/gen-pgbouncer-conf.bats
Invalid config can sneak in, resulting in confusing error messages. This commit attempts to validate entries in `PGBOUNCER_URLS` before passing them to the config. It handles two cases - the empty case, and the invalid PostgreSQL connection string case.
Fixes #171
=> fix: validate PGBOUNCER_URLS on config gen

.github/workflows/tests.yml, Changelog.md, Dockerfile, bin/compile, bin/start-pgbouncer, test/test-stack.sh
This commit adds a Dockerfile to build and run the buildpack in a Heroku-like environment to test for compability, and actually execute PgBouncer. It connects over a Unix socket to the management DB and checks the currently running version, then exits.
Additional changes are made to `bin/compile` and `bin/start-pgbouncer` to support this testing.
Fixes #165
=> test: add Heroku stack testing

Changelog.md
To pick up these changes:
https://github.com/heroku/heroku-buildpack-pgbouncer/compare/v0.13.0...f1c70d385d21f4beeeba859a83582d4d1da7b7e6
After this merges I'll Git tag and publish to the buildpack registry (since this buildpack lives under the `heroku` namespace on the registry, only the Languages team is able to publish, since a single team has to own the whole namespace).
=> Prepare buildpack release v0.14.0

Changelog.md, README.md, bin/gen-pgbouncer-conf.sh, test/gen-pgbouncer-conf.bats
In order to support SCRAM support for the new Heroku Postgres "Essential" plans, we need to shift from MD5 hashed passwords in `auth_file` to plain text. This does not materially change the threat model, as anyone with dyno access can read the passwords from the environment just as well as the file.
See: https://www.pgbouncer.org/config.html#authentication-file-format for more.
This commit switches the `auth_type` to `scram-sha-256` and also pushes `server_tls_sslmode` up to `require` over `prefer`.
Why not use a method like `auth_query`? Exposing something like `pg_authid` or `pg_shadow` in a safe way via a `SECURITY DEFINER` function is extremely challenging in a multi-tenant environment. This may change in the future.
Fixes #155.
Ref: https://gus.my.salesforce.com/a07EE00001rjvVBYAY …
=> maint: enable SCRAM support

Changelog.md
To pick up #195.
https://github.com/heroku/heroku-buildpack-pgbouncer/compare/v0.15.0...a68bddc34256a0e518085f8b5a63d8b988fde997
=> Prepare buildpack release v0.16.0

Changelog.md, bin/gen-pgbouncer-conf.sh, test/gen-pgbouncer-conf.bats
With much thanks to @zyv, this commit adds support for URI-encoded user/pass combinations. We decode URI-encoded user/pass combinations for use in `users.txt`, but keep the encoded versions for the exported pgBouncer URIs.
Ref: https://github.com/heroku/heroku-buildpack-pgbouncer/pull/139
=> feat: add support for uri-encoded user/pass

Changelog.md, README.md, bin/gen-pgbouncer-conf.sh, test/gen-pgbouncer-conf.bats
Following issues I had when using this buildpack with Prisma ORM and prepared statements, I am suggesting these changes to add support for `max_prepared_statements` configuration on pgbouncer.
As it turns out, it seems that if not set, the default value would be 0. This is an issue when using transaction pooling mode, and prevents from using prepared statements in that case.
Giving control to the user on this important configuration seems appropriate, keeping the default value at zero to avoid breaking changes, basically making it an opt-in config.
I updated the *.tgz files but I'm not sure this was needed as I'm not familiar with how build packs work, maybe the changes to `bin/gen-pgbouncer-conf.sh` were enough. Let me know so I can update my branch accordingly.
Relevant issues:
- Update …
=> Add `PGBOUNCER_MAX_PREPARED_STATEMENTS` config

Changelog.md
This commit prepares for release, adding a new changelog entry for v0.17.0
=> release: prepare v0.17.0
